emilsvennesson/script.module.inputstreamhelper

- lib/inputstreamhelper.py
This is compatible with python3 and python 2.7 (krypton and leia).
> fix python3 compatibility

- resources/language/resource.language.nl_nl/strings.po
I created a Dutch translation for this module.
> New language: Dutch

- lib/inputstreamhelper.py
This automatically updates widevine when inputstreamhelper is updated and running for the first time
> update widevine when new inputstreamhelper version first runs

- addon.xml
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/59
> 0.3.5 release

- .gitignore
- .travis.yml
- Makefile
- __init__.py
- addon.xml
- lib/config.py
- lib/inputstreamhelper.py
- pylintrc
- requirements.txt
- resources/__init__.py
- tox.ini
- Add sanity testing, including Travis
- Fix all pylint and PEP8 issues
- Add pip requirements.txt
- Add a Makefile for creating a working ZIP package
This relates to #63
> Add sanity tests

- addon.xml
- lib/inputstreamhelper.py
- Replace requests library with urllib/urllib2
- Increase download chunk size by factor 32 to speed up transfer
This fixes #64
> Replace requests and urllib3 with urllib/urllib2

- .travis.yml
- README.md
- addon.xml
- changelog.txt
- lib/inputstreamhelper.py
- pylintrc
- Required sanity fixes for Travis CI pylint
- Add badges to the README.md
- Improve the changelog.txt
> A few more sanity fixes on Travis CI

- addon.xml
- lib/inputstreamhelper.py
- resources/language/resource.language.en_gb/strings.po
This PR adds proxy support to the requests call using the global Kodi
proxy settings.
This fixes #50
> Add proxy support (on-the-fly)

- lib/inputstreamhelper.py
This output shows the error that this PR resolves. My system does not have loop and the check for it fails. This resolves the check error.
https://pastebin.com/4wqVCPcZ
> Fixes a python "No such file or directory" error

- lib/inputstreamhelper.py
The current code is calling platform.system() a lot of times, rather
than remembering the value once. This fixes that.
This fixes #79
> Ensure platform.system() is run just once

- lib/inputstreamhelper.py
- resources/language/resource.language.en_gb/strings.po
- Replace the defunct `DialogBusy()` with a `DialogProgress()` window
- Remove unneeded OK windows
- Add short English translation messages to make code more readable
- Includes small fixes for #62 
This fixes #70
> Add proper progress dialog for extraction

- lib/inputstreamhelper.py
This is a first attempt to handle an exception from `platform.system()`
This fixes #79
> Handle IOError: [Errno 10] No child processes

- .gitignore
- .travis.yml
- Makefile
- lib/inputstreamhelper.py
- pylintrc
- requirements.txt
- test/kodi_six/__init__.py
- test/kodi_six/utils.py
- test/kodi_six/xbmc.py
- test/kodi_six/xbmcaddon.py
- test/kodi_six/xbmcdrm.py
- test/kodi_six/xbmcgui.py
- test/kodi_six/xbmcplugin.py
- test/kodi_six/xbmcvfs.py
- test/test_ishelper.py
- test/userdata/addon_settings.json
- test/userdata/global_settings.json
- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcgui.py
- test/xbmcvfs.py
- Added stub kodi modules
- Added sample config files
- Integrate with Travis
This fixes #63
> Implement preliminary integration tests

- Makefile
- addon.py
- addon.xml
- lib/inputstreamhelper.py
- resources/language/resource.language.en_gb/strings.po
- resources/settings.xml
- A Troubleshooting category with the option to disable the plugin
- Add an item to install Widevine CDM
- Add an item to remove Widevine CDM
- Add an API (addon.py) using script.module.routing
This fixes #32, #47, #52, #54 and #77
> Implement settings menu and API

- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
These are older fixes that I saved for when we were going to rework the
dialogs. But maybe it's better to do it now.
> Dutch translation fixes

- lib/inputstreamhelper.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- A new localize() function for translating strings
- Improve log() to support placeholders
- Use named placeholders for translations and logs
> Use named placeholders for translations and logs

- .gitignore
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
Ensure all translated strings are available in all languages.
> Translate to Dutch and prepare translations

- lib/inputstreamhelper.py
- Ensure the mountpoint is not mounted before starting extraction
- Ensure multiple mounts are unmounted
This fixes #107
> Ensure mountpoint is unmounted properly

- Makefile
- lib/inputstreamhelper.py
- pylintrc
- test/test_ishelper_lin_arm.py
- test/test_ishelper_lin_x64.py
- test/test_ishelper_mac_x64.py
- test/test_ishelper_win_x64.py
- test/xbmcextra.py
- test/xbmcgui.py
This performs integrations tests for:
- Linux x86_64
- Linux ARM
- Windows x86_64
- Darwin x86_64
This fixes #116
> Add platform integration tests

- resources/language/resource.language.de_de/strings.po
Translate new strings to german.
> Update German translations

- resources/language/resource.language.nl_nl/strings.po
I  updated some Dutch language strings for #113
> Updated: Dutch Language

- .coveragerc
- .gitignore
- .travis.yml
- Makefile
- README.md
- requirements.txt
This PR adds coverage support.
> Add coverage support

- resources/language/resource.language.de_de/strings.po
Adding to the work of @flubshi . #120
> Small improvements to german translation.

- .coveragerc
- Makefile
And an excuse to test coverage support.
> Small fixes

- .travis.yml
- test/test_routing.py
This PR fixes:
- Coverage for running addon.py
- Coverage for widevine_remove route
> Various coverage improvements

- .coveragerc
- lib/inputstreamhelper.py
- pylintrc
- test/test_ishelper_android_arm.py
- test/test_ishelper_linux_arm.py
- test/test_ishelper_linux_x64.py
- test/test_ishelper_macos_x64.py
- test/test_ishelper_windows_x64.py
More experiments with coverage.
> More coverage improvements

- addon.xml
Add more information to the Kodi.tv website.
> Add more project information

- lib/inputstreamhelper.py
- Fixes to fdisk and parted parsing (required for local unittesting on Linux)
The new processing makes parsing the image more reliable and better future-proof.
> Fix ARM processing in unittest locally

- addon.xml
@emilsvennesson @dagwieers @basrieter After the blocked 0.4.0 release, I think this one will comply with Kodi add-on structure rules: https://kodi.wiki/view/Add-on_structure
> 0.4.1 release

- .coveragerc
- .github/codecov.yml
- .travis.yml
This will work somewhat better for our project.
> Clean up coverage/codecov config

- addon.py
- lib/config.py
- lib/inputstreamhelper.py
- resources/language/resource.language.en_gb/strings.po
- resources/settings.xml
- test/test_api.py
- test/xbmcgui.py
Implementing #87 . Tested on Ubuntu x86_64 and Libreelec RPi3. The content of the settings is filled after the first run.
> Add About category to settings page.

- addon.xml
This pull request includes the following changes to addon.xml:
- added standalone directive to xml declaration
- edit addon element attributes order
- added required summary element
- clean up spacing
> make sure addon.xml meets all requirements

- lib/inputstreamhelper.py
This reverts commit 0993eef6f5660d871559428cf89560bc9bff8f29.
> Revert "Fix ARM processing in unittest locally (#129)"

- resources/language/resource.language.fr_fr/strings.po
The contributed translation was based on the v0.4.1 release.
> Update french translation with missing strings

- .pylintrc
- Makefile
- lib/inputstreamhelper/__init__.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- test/test_api.py
- test/test_ishelper_android_arm.py
- test/test_ishelper_linux_arm.py
- test/test_ishelper_linux_x64.py
- test/test_ishelper_macos_x64.py
- test/test_ishelper_windows_x64.py
- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcextra.py
- test/xbmcgui.py
- test/xbmcvfs.py
- Change "ChromeOS" to "Chrome OS" in translations
- Port changes to XBMC stubs
- Fix pylint issues
> Assorted fixes to translations and testing

- .github/codecov.yml
- setup.py
- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcextra.py
- test/xbmcgui.py
- test/xbmcvfs.py
- Fixes to coverage reporting
- Backports for xbmc test framework (it's getting better all the time)
> Backport xbmc fixes, fix coverage

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/config.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- resources/settings.xml
- test/userdata/addon_settings.json
Before really looking into #165 I thought I'd quickly add this. Tested it a bit, seems to work well.
> Make update frequency configurable.

- Makefile
- lib/inputstreamhelper/__init__.py
- test/xbmc.py
When running tests, we should create the full path.
> create all folders in temp path

- lib/inputstreamhelper/__init__.py
- resources/settings.xml
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/131
> fix crashes when inputstream addon is missing

- Makefile
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
This pull request includes:
- update language files for translators
- add language test
> update language files

- Makefile
Fixes an error when temp dir doesn't exist
> clean userdata except settings

- addon.xml
- resources/language/resource.language.el_gr/strings.po
And the addition of el_GR summary on addon.xml
> Update greek strings.po for 0.4.3

- .pylintrc
- test/userdata/addon_settings.json
- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcextra.py
- test/xbmcgui.py
We now no longer write settings changes.
> Backport xbmc stubs and avoid writing

- Makefile
- lib/inputstreamhelper/__init__.py
- A small fix preventing chromeos_version to be displayed
- Improvements to Makefile
> Fix issue preventing chromeos_version in info

- resources/language/resource.language.sv_se/strings.po
Sorry for missing the deadline!
> Updated Swedish translation for 0.4.3

- Makefile
- README.md
- addon.xml
Preparing for the v0.4.3 release:
- updated README
- updated addon.xml
> 0.4.3 release

- resources/language/resource.language.nl_nl/strings.po
After reviewing new strings for inputstream.adaptive I reviewed this translation to ensure consistent language is used. No grave errors were found, just some small improvements.
> More consistent language.

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodehelper.py
- Delayed imports
- Selective imports
- Fix flake8 issues
- Extend to_unicode/from_unicode interface
> Assorted changes

- .pylintrc
- lib/inputstreamhelper/__init__.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- test/xbmc.py
- test/xbmcgui.py
This will indefinitely progress from 0% to 95% until the extraction is
completed. Start strong at the start and slowing down when it
progresses in order to reach 95%.
This fixes #105
This relates to #218
> Implement progress bar for extraction

- resources/language/resource.language.sv_se/strings.po
making the translations more consistent
translated untranslated words
minor tweaks
> Updating Swedish language

- lib/inputstreamhelper/__init__.py
This should fix `UnicodeDecodeError` in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/210
@dagwieers @janhicken @GitUser4711  Please test.
> Convert subprocess output to unicode

- .travis.yml
- Makefile
- tox.ini
This adds support for testing Python 3.5.
> Add Python 3.5 testing support

- resources/language/resource.language.hr_hr/strings.po
> Add Croatian translation

- lib/inputstreamhelper/__init__.py
A small formatting issue in the output.
> Fix formatting

- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
added Japanese and Korea translation
> Translation JP/KR

- .github/codecov.yml
- .gitignore
- .pylintrc
- .travis.yml
- Makefile
- default.py
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- test/test_proxy.py
- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcextra.py
- test/xbmcgui.py
- test/xbmcvfs.py
- Make use of the jsonrpc() function
- Introduce addon_profile() (replacing get_userdata_path)
- Update xbmc stubs
> Port new kodiutils changes and stubs

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodehelper.py
This fixes docstrings as done in other projects.
> Fix docstrings

- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
> Change rollback to restore.

- Makefile
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodehelper.py
- test/test_ishelper_android_arm.py
- test/test_ishelper_linux_arm.py
- test/test_ishelper_linux_x64.py
- test/test_ishelper_macos_x64.py
- test/test_ishelper_windows_x64.py
- test/test_proxy.py
This ensures that we are not suppressing things that aren't being
raised to begin with (i.e. because we fixed the underlying cause).
> Report pylint useless suppressions

- resources/language/resource.language.hr_hr/strings.po
#30821 and #30915 translated issue: #256
> Update hr_hr translation

- resources/language/resource.language.it_it/strings.po
Added missing lines as requested in #256
> Italian updated for 0.4.4

- README.md
- addon.xml
- resources/language/resource.language.de_de/strings.po
Preparing for the v0.4.4 release:
- updated README
- updated addon.xml
- remove newline in German strings.po
> v0.4.4 release

- addon.xml
- setup.py
Make sure users and developers know that this project is completely compatible with Python 2 and Python 3.
> Indicate Py2/3 compatibility

- lib/inputstreamhelper/__init__.py
This fixes #191 .
I did a quick test on Linux x86. Seems to work fine. Since it's not a big change I don't really expect any issues on ARM either.
> Change when last_update is set

- lib/inputstreamhelper/__init__.py
> Fix error with links if backup and cdm are on different drives.

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- test/xbmcgui.py
- test/xbmcvfs.py
This pull request adds compatibility with Kodi 19 Python API while preserving backwards compatibility with earlier Kodi versions.
> Add compatibility for Kodi 19 Python API

- resources/language/resource.language.ro_ro/strings.po
Translated strings into Romanian for the first time.
> Add Romanian translation

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
I think this change can be merged rather quickly, since it really only moves functions somewhere else, imports them and renames stuff where necessary.
> Restructure

- lib/inputstreamhelper/utils.py
I am not fond of the new `store()` functionality as it requires a
synchronous approach to where specific cached information is set and
used.
And I understand how it can help with the image-processing
functionality, however I think this mostly is a display of bad practices
and actually requires a redesign of the progress-bar and how we call each phase.
This PR returns back to the original "if cached, return cache, otherwise
perform lookup" for a simple case, but I'd like to see a different
approach to the other uses.
> Make functions cache values

- lib/inputstreamhelper/__init__.py
While rebasing something I'm working on I saw this. Change to a different level if you prefer.
> Fix overlooked call to log()

- lib/inputstreamhelper/widevine/arm.py
Adding 20 MiB buffer to the required disk space won't hurt and possibly fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/281
> Add a 20 MiB buffer to required disk space

- README.md
- addon.xml
Just another release to test automatic submission to Kodi repo. (https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/299)
> v0.4.6 release

- lib/inputstreamhelper/utils.py
This is fixed by moving the "import" into the error handling.
> Closes #331

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodes.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
- tests/xbmc.py
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/333
> Support unicode chars in paths

- README.md
- addon.xml
Hotfix release for https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/333 and https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/331
> v0.4.7 release

- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/arm_chromeos.py
- resources/language/resource.language.en_gb/strings.po
Here are some small improvements to #348 as discussed there, including
* comments where assumptions are made
* a slightly improved progress dialog
* get_bstream is now a static method
> Improvements for #348

- lib/inputstreamhelper/__init__.py
This relates to #351 and fixes it for those who already have widevine installed.
> Handle missing widevine config or unknown latest version in update_widevine

- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/widevine.py
* Increases timeout (relates to #305)
* Creates option to download in background, uses it for EULA
* Only shows remaining time after it stabilized a little (both requested here https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/348#issuecomment-624050171)
> Various improvements to download

- resources/language/resource.language.ro_ro/strings.po
Translated to Romanian new added strings
> Translate new added strings to Romanian

- resources/language/resource.language.el_gr/strings.po
Filled #30058, #30059, #30060, #30061, #30062, #30063, #30064, #30065, #30800, #30810, #30811, #30820, #30821, #30822, #30823, #30824
> GRstrings for 0.5.0

- .github/workflows/addon-check.yml
- .github/workflows/ci.yml
- .pylintrc
- Using upstream sonarcloud action with new functionality
- Revert back to using kodi-addon-checker pip package
> Clean up workflows

- README.md
The code example didn't work in some cases. We need to set the listitem type to video.
> Fix InputStream Helper Demo

- tests/checkchromeos.py
Fail the status check when online resources are not available.
> Raise exception for bad http status codes

- lib/inputstreamhelper/kodiutils.py
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/444
> Fix unicode bug

- lib/inputstreamhelper/__init__.py
- resources/settings.xml
This fixes #451 .
Should we maybe make the time configurable? I don't think it's really necessary.
> Postpone update by 2 days if declined by user

- .github/workflows/addon-check.yml
- .github/workflows/release.yml
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.en_gb/strings.po
- resources/settings.xml
This could definitely be improved. But if the code works and after some testing I would like to do a release soon. Especially because of #495  and the fix #496.
Fixes #497
> Add option to install Widevine from ChromeOS image specified by URL or local

- lib/inputstreamhelper/utils.py
- resources/settings.xml
Also, slightly restructures Debug settings.
> Fixes update_frequency setting falsely disabled.

- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
No config.json was created and thus the version couldn't be determined reliably.
> Fix issue with new install_from option

- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/arm_chromeos.py
> Properly search the filesystem instead of simply detecting the filename in the bytestream

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/widevine/widevine.py
This adds Widevine support for Mac computers with ARM64 architecture (Apple M1)
Please test, I don't own Apple hardware myself.
> Add Widevine support for ARM64 Mac

- lib/inputstreamhelper/utils.py
- resources/language/resource.language.en_gb/strings.po
> If the checksums or filesizes do not match after download, ask if we should continue.

- lib/inputstreamhelper/widevine/arm_chromeos.py
- resources/language/resource.language.en_gb/strings.po
> Improvements to arm_chromeos.py

- lib/inputstreamhelper/utils.py
> Implement own "Version" class to get rid of distutils/packaging dependency
