- lib/inputstreamhelper.py
Currently plugin crashes when there is some Unicode character in users profile path.
`WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\V\xc3\xa1clav\\AppData\\Roaming\\Kodi\\cdm/*.*'`
This PR should fix it - convert this path to utf-8 at first, because some functions in python 2 expecting path in utf-8 (or something like that :) )
> Support for Unicode paths in Windows

- addon.xml
- lib/config.py
- lib/inputstreamhelper.py
Only three small changes were necessary to make this script module work on Kodi Python3.
Tested with the following installations:
- Kodi Python3 test-build on Windows 10 x64: http://mirrors.kodi.tv/test-builds/windows/win64/
- Kodi Python2 on Ubuntu 18.04
- Kodi Python2 on LibreELEC 9.0.1
> fixed kodi python2_3 compatibility

- lib/inputstreamhelper.py
When inputstream.adaptive is not installed, install it.
Because of a bug upstream, for now you have to restart Kodi to get the binary addon inputstream.adaptive working.
But this Kodi bug is already fixed in de nightly builds: https://github.com/xbmc/xbmc/pull/15780
> auto install inputstream.adaptive when not installed

- lib/config.py
- lib/inputstreamhelper.py
- Move to using versions.txt instead of current.txt for non-ARM platforms
- Update ARM hwid from SPRING to SKATE (smallest and latest ARM image)
- Decrease the version check from 30 days to 14 days
- Use a better formatted link
This fixes #59
> Use versions.txt to get the latest version

- resources/language/resource.language.nl_nl/strings.po
The file was previously encoded in Western ISO
UTF-8 is a requirement for official Kodi repo.
> convert Dutch strings.po to UTF-8

- lib/config.py
- lib/inputstreamhelper.py
Since the legacy widevine version is no longer supported, and the newer
widevine versions are only supported by Kodi v18, there is no need to
keep legacy support around.
This fixes #66 
This relates to #35
> Remove legacy support

- lib/inputstreamhelper.py
This updates the error to check that the arm64 kernel is running in a 64-bit userspace before it throws a warning.
> Support 64-bit kernel with 32-bit userspace

- lib/inputstreamhelper.py
I'm using buildroot, and modprobe doesn't run unless the check_output command is run using shell=True. This pull request adds an additional optional parmater to the run_cmd definition that tells it whether to run as shell, and then passes that parameter as true when calling modprobe for the checkloop method.
> ModProbe needs to run as shell on some systems

- lib/config.py
- lib/inputstreamhelper.py
Rather than pre-selecting a specific device (which may get unsupported
or stale suddenly) it is better that we select an ARM device image that
fits our purpose: the latest version that is the smallest in size
This implements this better selection, and instead of `SKATE` we now use `BIG`.
Since the `SKATE` image is now older than `BIG`. `SKATE` is now stale.
This fixes #62
> Select the best ARM image available

- lib/inputstreamhelper.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/settings.xml
As stated in #32 with this change you can enable/disable inputstreamhelper via GUI at 
"kodi settings" > "system" (change from standard to expert there) > "addons" > "manage dependencies" > "Inputstream Helper" > "configure".
> Make option to disable module visible in GUI

- lib/inputstreamhelper.py
- test/kodi_six/utils.py
This reverts a previous fix https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/48#issuecomment-474529285
We are now using `unicode_literals` and this old fix became counterproductive.
> fix unicode error

- addon.py
- lib/config.py
- lib/inputstreamhelper.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- test/xbmc.py
This pull request includes:
- fix for removing Widevine on Windows
- move `remove_widevine` to Helper class
- always use Kodi CDM dir to install Widevine CDM to, phase out use of inputstreamhelper addon data CDM dir
- determine widevine path based on static filename (just like InputStream Adaptive does)
- wait until InputStream Adaptive installation is complete (xmbc.executebuiltin wait parameter)
- use notification dialogs when installing or removing Widevine CDM
> directly remove and install Widevine in Kodi CDM dir

- lib/inputstreamhelper.py
This forces bytestrings for python 2 os.walk, related to https://bugs.python.org/issue22862
> force bytestring for os.walk

- addon.py
- addon.xml
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- A fix for the double plugin icons
- A workaround for a script.module.routing bug
- Visual fix for the settings
This fixes #108
> Ensure only a single plugin icon

- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
Since this option will also reinstall Widevine CDM if it was already
installed, we want to add this subtlety.
This relates to #101
> Use "(Re)install Widevine CDM" for settings

- lib/inputstreamhelper.py
Since we no longer use symlinks for the Widevine CDM, we remove any symlink before extraction.
This fixes #109 and relates to #108
> Remove (dangling) symlinks before extraction

- README.md
`changelog.txt` is no longer parsed by Kodi and I had to remove this file to get the 0.4.1 release accepted in the official repo.
This pull request moves the release history to README.md
> move releases to readme

- addon.py
- lib/api.py
The python files refered in addon.xml won't get compiled to bytecode, so we have to keep addon.py short and simple to speed up loading times.
> simplify entry point to speed up loading time

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- resources/settings.xml
- test/test_api.py
- test/xbmcextra.py
- test/xbmcgui.py
The reason to rename the 'About' dialog to 'InputStream Helper
information' is that it is clearer to the user where the information is
coming from exactly.
As we expect developers to use this from their own add-on for
troubleshooting purposes, it is important to make clear what it is about
(pun intended).
- Renaming About dialog in Info dialog
- Dutch translations
- Localize '(disabled)' string
- Restructure translation strings (30800: information, 30900: settings)
- Prepare translation to other languages
- Small visual improvements
> Rename 'About' into 'IS Info'

- README.md
- addon.xml
Because 0.4.1 with https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/0993eef6f5660d871559428cf89560bc9bff8f29 broke libwidevinecdm.so extraction from Chrome OS, I reverted this commit. Now we need to release a 0.4.2 version so InputStream Helper is functional again for people using platforms like Rpi and Odroid.
@basrieter @dagwieers @emilsvennesson Please test and approve
> 0.4.2 release

- test/xbmc.py
- test/xbmcaddon.py
- test/xbmcgui.py
This makes it possible to change the locale.language in the global
settings and get localized translations in testing output.
> Implement translation tests

- addon.xml
In the alpha versions of Kodi 19 "Matrix" the InputStream Helper icon is not visible. This pull request fixes this.
Tested already on Linux, Windows and LibreELEC and this doesn't change behaviour on Kodi 18.x
Please test this on other platforms.
> fix visibility in kodi 19

- addon.xml
- default.py
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/unicodehelper.py
This pull request fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/102 and includes:
- remove kodi.six dependency
- replace `os.path.realpath(__file__)` with` xbmcaddon.Addon().getAddonInfo('path')` because it failed on `C:\Users\Björn` unicode path
- add unicodehelper file with conversion functions
- ensure global var ADDON_VERSION is reused
- convert to/from unicode when necessary for xbmc python2 functions
> consciously use unicode

- lib/inputstreamhelper/__init__.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- resources/settings.xml
- test/userdata/addon_settings.json
- test/xbmc.py
- test/xbmcgui.py
> Custom path for ARM devices with limited space

- Makefile
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
- resources/settings.xml
It seems most other add-ons use "Expert" which better fits this section
here as well.
Also, even (or especially) when InputStream Helper is disabled the user
may want to install or remove Widevine. So it does not make sense to
disable this functionality when InputStream Helper is disabled.
I also added separators since having more than one section seems worse
than this.
- Reorganization of settings
- Rename "Troubleshooting" into "Expert"
- Turn frequency into slider
- Restore default frequency from "14" to "31"
> Rename "Troubleshooting" to "Expert"

- lib/inputstreamhelper/__init__.py
So we don't have to translate the path ourselves, this is what
_temp_path() will do for us.
So after writing the (new?) setting we can compare it to the old setting
to ensure it conforms to the same manipulations.
This fixes #186
> Translate path and compare before moving

- resources/settings.xml
Sadly I didn't think of this before and noticed this just yet on Android.
There is no need for having any of the inputstreamhelper options on Android.
> Disable all options on Android

- .pylintrc
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
Importing modules at function level is considered a bad practice in pylint 2.4, this pull request moves all imports to module level.
> fix new pylint v2.4 tests

- lib/inputstreamhelper/__init__.py
- requirements.txt
- resources/language/resource.language.nl_nl/strings.po
Since Android ships with Widevine, our current information on Widevine
is broken for Android. This PR disables the Widevine section on Android.
This fixes #204
> Remove Widevine information on Android

- lib/inputstreamhelper/__init__.py
- test/test_proxy.py
We added retries to our HTTP requests because of issues with proxy.py
and Python 2.7 (causing BadStatusLine issues).
Since this is a pure proxy.py issue, I'd rather stop testing proxy
compatibility on Python 2.7 then changing our code to support tests
(most of the time).
> Disable proxy tests on Python 2.7

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
Since making a screenshot is harder than copy&pasting logs, it is
probably better to log this information as well when it is requested.
This may help in troubleshooting.
This relates to #206
> Add InputStream Helper information to logs

- lib/inputstreamhelper/__init__.py
For some reason unclear yet, I ended up with a widevinecdm.so that had
size 0, so obviosuly it didn't match the regexp and match would be None.
Resulting in:
```
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py",
line 244, in _get_lib_version
return match.group(0).lstrip('0')
AttributeError: 'NoneType' object has no attribute 'group'
```
> Support undetected version

- .gitignore
- .pylintrc
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- test/xbmcgui.py
These are all changes unrelated to autoanswer, but needed for the
ok_dialog and yesno_dialog implementation.
- Wrappers for dialog functions
- Delayed imports for xbmcgui
- Ignore addon_data directory
This relates to #198 and is required for #202 
And it conflicts with #219 :-)
> Assorted fixes (needed by autoanswer)

- lib/inputstreamhelper/__init__.py
May be controversial, but if we want to keep inputstreamhelper's
footprint as small as possible to add-ons using it, this may help.
To be discussed.
> Move imports to where they are being used

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/kodiutils.py
- resources/language/resource.language.en_gb/strings.po
- resources/settings.xml
- test/xbmcgui.py
- test/xbmcvfs.py
This adds the option to automatically create a backup of the installed lib (on update/reinstall or rollback) and rollback, keeping multiple backups according to the setting 'backups'.
This does not yet implement online rollback or pinning, but I think we should discuss (in #165) whether pinning is actually any different from disabling.
> backup and local rollback

- lib/inputstreamhelper/__init__.py
If `LANG=de_DE.UTF-8` is used, for example, the command output of `fdisk -l` will contain unicode characters. This is problematic because Kodi's logging mechanism crashes and the command's output parsing is not reliable.
When `LANG=C` is used, the commands' output will consist of ASCII-only characters, which is nice.
See #210 for an example of the resulting error message when a unicode string is given to the `log()` function. As every command output is given to `log()`, this means bad things.
> Use LANG=C for subprocesses

- lib/inputstreamhelper/__init__.py
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/220
I tested this on a x86-64 Linux system and it should work for paths with or without spaces with `fdisk` and with `parted` both on `python2` and `python3`.
Not yet tested in a real life Kodi environment! Please test with different temporary download directories on different ARM systems with `parted` and `fdisk` before merging!
> support paths with spaces when calculating Chrome OS losetup offset

- resources/settings.xml
We currently have the id attribute added to entries in the settings.xml
that don't need it. And this results in entries in the user's settings
for things that don't store values.
So we ought to remove them to keep the user settings clean (for new users).
> Remove id from settings entries

- lib/inputstreamhelper/__init__.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
Rather than leaving Widevine information out of the information pane, we
should display it as 'built-in'. This will be less confusing.
This relates to #206
> Add Widevine version as built-in

- lib/inputstreamhelper/__init__.py
It's more efficient to use a binary regex when looking for something in a binary file. We only need to convert to a unicode string if something is found.
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/250
> Use binary regex on binary lib

- lib/inputstreamhelper/kodiutils.py
- test/xbmcgui.py
`select_dialog` was broken, this pull request makes it functional. (function is used for restoring an earlier Widevine CDM library)
> Fix select_dialog function

- lib/inputstreamhelper/__init__.py
It seems using the missing os.link in Python2 on Windows gives an AttributeError instead of OSError. This commit corrects that. See https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/256#issuecomment-582587377
> Change OSError to AttributeError

- lib/inputstreamhelper/__init__.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
This displays the unsupported architecture in the dialog to the user.
It also fixes an incorrect reference to {os}.
This relates to #268
> Show unsupported architecture in pop-up

- lib/inputstreamhelper/__init__.py
- test/xbmcvfs.py
I tested the following script on an RPi3 using Raspbian:
```python
from hashlib import md5, sha1
from datetime import datetime
def check(alg):
with open("chromeos_12607.82.0_nyan-kitty_recovery_stable-channel_kitty-mp-v2.bin.zip", "r") as f:
starttime = datetime.now()
print("{} started at {}".format(alg, starttime))
if alg == 'md5':
checksum = md5()
should_be = '245b4eb00dba6752b0038ba447440799'
elif alg == 'sha1':
checksum = sha1()
should_be = '86afee8b24784947cfecbc49a42fe58538a003b5'
else:
print('Specify sha1 or md5')
return
while True:
chunk = f.read(32*1024)
if not chunk:
break
checksum.update(chunk)
h = checksum.hexdigest()
print("Calculated {} with hexdigest {} at {} after {}".format(checksum, h, datetime.now(), datetime.now() - starttime))
if h == should_be:
print('Checksum …
```
> Add option to calculate checksum in _http_download()

- lib/inputstreamhelper/__init__.py
On bad connections,  a single chunk download can fail, causing the entire download to fail. Adding this timeout fixed it on my bad connection.
Fixes #274
> Add a 5 second timeout for chunk download

- lib/inputstreamhelper/__init__.py
This fixes a possible unicode error when `_run_cmd` fails
> Add missing to_unicode

- lib/inputstreamhelper/__init__.py
At some point, `show_versions` was changed, breaking the implementation removing the installed version. Applying it to `versions` before producing `show_versions` fixes that.
> Fix rollback installed_version not in list

- .codecov.yml
- default.py
- lib/inputstreamhelper/api.py
- A note explaining why we need to modify the python library path
- Rename 'rollback' method to 'widevine_rollback'
- Add a proper error when method was not known
- Move codecov config, hoping this fixes codecov reporting
> Explain why we need to modify the python library path

- default.py
- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
Many thanks to @enen92 for figuring this solution out.
Meanwhile I tested this on the following systems and it just works fine!
- Kodi 19.0-ALPHA1 Git:20200226-cde760b94e on Windows x64
- Kodi 18.6 on Linux x64 and Windows x64
- LibreELEC 9.2.0
- LibreELEC 8.2.5
> Use explicit relative imports instead of sys.path.append

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodes.py
- lib/inputstreamhelper/utils.py
I moved `http_request`, `http_get`, `http_download`, `temp_path` and `update_temp_path` to utils.py, with some necessary changes. Hopefully I managed not to break any other PR.
At first I wanted to keep `from_unicode` and `to_unicode` in utils, but that would have resulted in circular imports between utils and kodiutils.
Maybe as a next step `unzip` (and `widevine_eula`?) could be moved to utils, too. Then there might be a better solution for `self._download_path`.
This relates to #94 .
> Restructure the code

- Makefile
- addon.xml
This adds support for automatically building a Kodi 19 Matrix compatible zip package with `make`.
This includes:
- automatically change the Python ABI version in addon.xml (change to **3.0.0** for Matrix)
- automatically change the addon version using local version identifier ([PEP-440](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers)) (add **+matrix.1** to current version for Matrix)
How to build:
```
cd script.module.inputstreamhelper
make multizip
```
> Support exporting Kodi 19 Matrix compatible zip package

- README.md
Replace the Travis CI badge with the one from GitHub CI.
> Add the new CI badge to the README

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/utils.py
- resources/settings.xml
These commits prepare the code for restructuring.
* Class attributes are changed to function attributes. That function can be imported where ever needed, so it works across files.
* `_widevine_eula` and the `_install_widevine*`s are changed to make sure the arch-specific functions don't need generic widevine functions. (That would create circular imports when restructuring.)
This also fixes what I mentioned in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/294#issuecomment-600465581
> Prepare restructure

- .github/workflows/release.yml
- Makefile
This automates future Github releases when pushing a version tag:
- reads latest changelog from README.md and adds this to the Github release
- automatic generation of zip packages for Kodi Krypton/Leia and Matrix
> Automate Github release

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/api.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
This pull request takes improvements from https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/240 that are ready to be merged:
- allow logging on different levels
- wrap file operations in kodiutils.py
- rework Widevine CDM detection functionality
- various spelling and log messages corrections
> Improve logging, file operations and Widevine CDM detection

- .github/workflows/ci.yml
- Makefile
Currently CI would fail on untranslated strings, but during development
this is to be expected. So we check now for both, but don't fail for
untranslated strings.
> Don't fail on untranslated strings

- lib/inputstreamhelper/utils.py
Since we call `arch()` all over the place, it is better to get it once,
report on it and cache the value for future use.
> Cache architecture information

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/widevine.py
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/294
It is confirmed this works to detect  64-bit userspace on ARM64.
Before merging, this should be tested more, especially on Android.
> Simplify userspace detection on ARM64

- lib/inputstreamhelper/kodiutils.py
I introduced a bug in https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/da9e10c729fedfb52eec2c5098741ed2556eface
In some specific cases the progress dialog would show duplicate lines. This pull request fixes this.
The new Python API in Kodi 19 was also broken: https://github.com/xbmc/xbmc/pull/17684
> Fix multi-line text in progress dialog

- resources/settings.xml
This pull request Improves settings behavior:
- hides Widevine settings on Kodi 17 Krypton
- fixes disabling Widevine settings when InputStream Adaptive is disabled or missing on Kodi 19
> Improve settings behavior for all supported Kodi versions

- lib/inputstreamhelper/kodiutils.py
- tests/test_ishelper_android_arm.py
- tests/test_ishelper_linux_arm.py
- tests/test_ishelper_linux_x64.py
- tests/test_ishelper_macos_x64.py
- tests/test_ishelper_windows_x64.py
- tests/test_proxy.py
- tests/test_utils.py
After https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/830cfb566133e8e925722bdafe623b5b65ecc420 was merged, unit tests didn't fully execute anymore because they used the cached property in `arch()`.
Deleting the cached property when executing unit tests solves this bug.
> Delete arch.cached property in unit tests

- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- tests/userdata/addon_settings.json
- tests/xbmc.py
- tests/xbmcaddon.py
In the past we never tested temp paths containing unicode characters and unicode bugs were left undetected. We could only fix these bugs after a user created an issue.
This pull request fixes a couple of unicode bugs and adds unicode chars to the tests temp_path in addon_settings.json.
> Use temp path with unicode chars for testing

- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.de_de/strings.po
- resources/language/resource.language.el_gr/strings.po
- resources/language/resource.language.en_gb/strings.po
- resources/language/resource.language.es_es/strings.po
- resources/language/resource.language.fr_fr/strings.po
- resources/language/resource.language.hr_hr/strings.po
- resources/language/resource.language.hu_hu/strings.po
- resources/language/resource.language.it_it/strings.po
- resources/language/resource.language.ja_JP/strings.po
- resources/language/resource.language.ko_KR/strings.po
- resources/language/resource.language.nl_nl/strings.po
- resources/language/resource.language.ro_ro/strings.po
- resources/language/resource.language.ru_ru/strings.po
- resources/language/resource.language.sv_se/strings.po
This changes the way the ChromeOS image is extracted and tracks the progress. It most probably fixes #325 .
With this change, the `unzip()` function isn't used anywhere at all, but I wasn't sure, if it should be removed.
> Track real progress of unzip in install_widevine_arm

- .pylintrc
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/arm_chromeos.py
- resources/language/resource.language.en_gb/strings.po
Okay, as promised in https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/319#issuecomment-623191660, here is another PR about installing Widevine on ARM.
It accesses the zipped image directly, and extracts the lib from it. On an RPi3 this takes around half the time it takes to extract the whole image and (obviously) only uses about one third of disk space.
I tested this on an RPi3 and it seems to work. The reason it's still a Draft PR is because the progress dialog needs improvement and there are some messages not yet localized (mainly in the progress dialog).
But you're welcome to test it already, the only changes I have planned are the two points mentioned above and they shouldn't affect the actual code.
This is based on #327 and (imho) supersedes #319 . It resolves …
> Access the zipped Chrome OS image directly

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/unicodes.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/arm_chromeos.py
This fixes some code style warnings:
- Fix E501 line too long
- Fix E226 missing whitespace around arithmetic operator
- Fix E303 too many blank lines
- Fix E124 closing bracket does not match visual indentation
- Fix E265 block comment should start with '# '
And also adds compatibility for unicode chars in paths:
- use `compat_path` when opening a full path with `open()` or `ZipFile()`
> Fix linting warnings and unicode compatibility

- lib/inputstreamhelper/utils.py
- resources/language/resource.language.en_gb/strings.po
This includes:
* Report free disk space if after download the filesizes do not match (as discussed https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/281#issuecomment-614294737)
* Retry downloading if it fails, base on code from @mediaminister here https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/305#issuecomment-627511506
This resolves #281 and fixes #305, but there are two points which I'd like to discuss before merging:
* `total_length` is a float, I think it should be int?
* What should be done if the `dl_size` (the zipfilesize of the Chrome OS image extracted from recovery.conf) does not match `total_length`?
> Improvements to http dl and request

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/widevine/widevine.py
- resources/settings.xml
- tests/userdata/addon_settings.json
This resolves the inconsistency between using last_update for when widevine was last installed and for when an update check was made.
This relates to #344.
> Changes to last_update

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
This changes recovery.conf to recovery.json, which is easier to load (see changes to `chromeos_config()`) and should be more future proof, since recovery.json is also used by the "Chromebook recovery utility" addon for Chrome browser.
Additionally it also only saves the data of the chosen image instead of the whole recovery.json, making it easier to read (and saving a tiny bit of diskspace).
> Changes to Chrome OS recovery

- lib/inputstreamhelper/widevine/arm_chromeos.py
This fixes #368.
The problem is that "libwidevinecdm.so" is somehow found twice in the Chrome OS image. I had actually noticed that before, but forgot about it again, otherwise I would have added this check earlier.
The other occurrence so far always was the second one, but now it was the first.
This change checks if the inode number is plausible and the name length matches and continues searching if it doesn't.
> libwidevinecdm.so exists twice in CrOS images

- lib/inputstreamhelper/kodiutils.py
If a progress dialog is initialized right after calling close() on another, it might happen that the previous progress dialog is still active and text from the previous dialog is displayed in the new one.
Checking if there is a progress dialog active and waiting until it closes before initializing a new one solves this problem.
> Wait for previous Progress dialog to close

- lib/inputstreamhelper/widevine/widevine.py
This prevents crashing `os.path.join` when opening the info screen when InputStream Adaptive is not installed.
> Fix info screen when IA is not installed

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/arm_chromeos.py
- lib/inputstreamhelper/widevine/widevine.py
This pull request adds optimizations to reduce the load on the file system:
- bugfix: add trailing file system separator (slash/backslash) to folder paths because `xbmcvfs.exists` needs this to succesfully check if a folder exists
- only create mount path when it will be used
> Optimize file operations

- lib/inputstreamhelper/widevine/arm.py
This directory also needs a trailing file system separator for `xbmcvfs.exists`
> Fix dir in legacy extraction

- resources/language/resource.language.nl_nl/strings.po
`{version}` was wrongly translated. This causes the information dialog to not show the version.
> Fix typo in dutch translation

- lib/inputstreamhelper/config.py
Apparently we have two incorrect Chromebook product types in our ARM
HWID list. We should probably investigate the others as well, and expand
the list with newer devices as well.
The incorrect HWIDs were:
- PHASER: MediaTek architecture
- PHASER360: Celeron architecture
This fixes #395
> Remove PHASER from ARM HWID list

- README.md
- addon.xml
This is an emergency release to fix an incorrect Widevine download
breaking existing ARM setups.
> Prepare for v0.5.1 release

- lib/inputstreamhelper/widevine/arm.py
This is crucial for our ARM users to understand a new Widevine was installed from a specific ChromeOS image.
Having this will make it much easier for users to idenfity the cause of their recent problems, as well as help us identify the affected ChromeOS image in case of issues.
> Log when we download a new ChromeOS ARM image

- .github/workflows/release.yml
This adds automatic submission of releases to https://github.com/xbmc/repo-scripts/ based on https://github.com/xbmc/action-kodi-addon-submitter
To make this functional, three secrets must be configured in this repo:
- EMAIL
- GH_USERNAME
- GH_TOKEN (needs public_repo scope and can be created at https://github.com/settings/tokens/new)
When pushing a new version tag (e. g. v0.5.2) to this repo, PR's will automatically be created at https://github.com/xbmc/repo-scripts/
> Submit releases automatically to Kodi repo

- lib/inputstreamhelper/config.py
- add new ARM hardware id's
- remove all end-of-life ARM hardware id's
- remove router hardware id's because they lack the widevine binary
- Slightly improve hardware id selection in `arm.py`
I used the following resources to update the list of hardware id's:
https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices
https://cros-updates-serving.appspot.com/
> Update Chrome OS ARM hardware id's

- lib/inputstreamhelper/kodiutils.py
- tests/xbmcvfs.py
[python] update xbmc.translatePath() to xbmcvfs
> [python] update xbmc.translatePath() to xbmcvfs

- lib/inputstreamhelper/kodiutils.py
- resources/settings.xml
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/388
I guess `xbmcaddon.getSettingNumber` isn't functional because you can only define an integer type in the Kodi addon settings xml and in addition it is wrongly named as `type="number"`.
Maybe this can be fixed upstream if Team Kodi still accepts changes to the deprecated old settings format:
https://kodi.wiki/view/Add-on_settings#type.3D.22number.22
Relevant source code
https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/addons/settings/AddonSettings.cpp#L832-L844
`setting->GetType() `can never be a `SettingType::Number`, so it differs from `TSetting::Type()` and returns false
https://github.com/xbmc/xbmc/blob/c4de26b28fb13ce65eb1caac4236d83bd410d112/xbmc/addons/Addon.cpp#L206 …
> Fix invalid setting type

- .github/workflows/status.yml
- tests/checkchromeos.py
This PR ads a daily status check to the github workflow to determine Chrome OS recovery image availability and includes the following features:
- status check fails when inputstreamhelper config contains missing or outdated(EOL) hardware id's
- status check succeeds when  inputstreamhelper config is up to date
- shows a message with the hardware id with  the smallest recovery image
This should fix https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/414
> Check Chrome OS recovery images availability

- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.en_gb/strings.po
- tests/xbmc.py
With the release of Widevine CDM 4.10.2252.0, Google uses a newer dynamic library that needs an operating system with TCMalloc support and a patched glibc to work. Support for this already implemented in LibreELEC and CoreELEC:
https://github.com/LibreELEC/LibreELEC.tv/pull/5376
https://github.com/CoreELEC/CoreELEC/pull/287
LibreELEC will release a new version supporting the new Widevine CDM: https://github.com/LibreELEC/LibreELEC.tv/pull/5399
This PR tries to handle some problems InputStreamHelper users will run into.
- propose the user to install an older Widevine CDM when `libtcmalloc_minimal.so` is not found.
- warn the user that Google will remove support for older Widevine CDM's on 31 May, 2021 when installing older CDM's
> Install older Widevine CDM when OS doesn't have TCMalloc support

- lib/inputstreamhelper/widevine/arm.py
This checks if TCMalloc is preloaded or linked using `/proc/self/maps`
> Improve TCMalloc detection

- lib/inputstreamhelper/widevine/arm.py
As discussed in https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450
> Check TLS 64bytes support by environment variable

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.en_gb/strings.po
This removes the deprecated method to extract Widevine from the Chrome OS image and everything associated with it.
I'm not sure about the strings.po files. i'll sync the other languages to the english file in a seperate PR, but is it ok, if some IDs in the middle are missing? Changing all the IDs of the following messages would be a rather big task which seems unnecessary to me.
> Remove deprecated install method on ARM.

- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.en_gb/strings.po
It makes no sense trying to install the older 4.10.1679.0 Widevine anymore since Google revoked it.
> Don't try installing revoked Widevine CDM

- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
- resources/language/resource.language.en_gb/strings.po
There is only one working Widevine CDM for ARM systems today and it needs a system that supports TLS 64-byte alignment. It doesn't make a lot of sense for ISH to detect if the users system is compatible. If not , Widevine will definitely fail and users should upgrade their system anyway.
> Remove TLS 64-byte alignment detection

- README.md
The old link with the example video was broken.
> Update video link in the example

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- lib/inputstreamhelper/widevine/widevine.py
`distutils` module is deprecated in Python 3.10: https://www.python.org/dev/peps/pep-0632/
PEP 632 recommends using `packaging.version` which is part of `setuptools`, but this is not a part of the standard Python library.
To support Kodi systems (e.g. Windows) that don't have `setuptools` installed, a fallback to `disutils` is still needed.
> Improve version checks

- lib/inputstreamhelper/utils.py
I tried the [proposal from DokuroKM](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495#issuecomment-1065477688) in issue #495, and this helped. 
I think the root cause is, that google changed the format of the information which the input stream helper uses to check the latest available widevine version.
On my system after the change of the local file `~/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py` the widevine update dialog was shown correctly and I was able to update. After the update everything worked as intented.
Can please someone review that and check that it has no side effects?
> Interpret http-get feedback as utf-8 (issue #495)

- lib/inputstreamhelper/widevine/arm.py
- tox.ini
Until now, select_best_chromeos_image actually only used less than half of the hwids in the list, since many don't have that space after the name.
In the long run, I think it is better to use the board names, since there are multiple hwids/code names which use the same image. The name of the image always contains the board name. That will also make life easier if they switch from the 32bit to 64bit lib, cause we only have to change one board name, instead of checking for all code names.
> Fix for select_best_chromeos_image.

- lib/inputstreamhelper/__init__.py
- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/kodiutils.py
- lib/inputstreamhelper/utils.py
- lib/inputstreamhelper/widevine/arm.py
- resources/language/resource.language.en_gb/strings.po
- tests/checkchromeos.py
- tox.ini
Closes #530 
So far only LAZOR (and some others which use the same image) has the 64bit library. We need to monitor the other images for when/if they make the switch.
The path for `find_file()` could be changed accordingly, since the lib is not in `arm_cros`, but `arm_cros64` in those images.
> Initial support of 64bit userspace on ARM

- lib/inputstreamhelper/config.py
- lib/inputstreamhelper/widevine/arm.py
- tests/checkchromeos.py
This avoids comparing multiple codenames with the same recovery image. Should speed things up a little.
> Replace Chrome OS code names with board names.

- lib/inputstreamhelper/widevine/widevine.py
Current implementation is broken, because it tries to fetch available Widevine repo versions from Linux/ARM64. As there are no such releases, it fails in retrieving a download link it can use to extract the EULA.
> fix EULA retrieval for linux/arm64

- README.md
- addon.xml
I decided on 0.7.0 for this version because we are removing support for Python 2.
@horstle, do you think we should include anything else in this version? I'd appreciate your eyes on this seeing as you've done the heavy lifting as usual. :-)
> prepare for v0.7.0

- lib/inputstreamhelper/config.py
Not many current 32bit images left...
> Updates Chrome OS board names.

- lib/inputstreamhelper/utils.py
#575
```15699.72.0``` gets parsed as ```15699.72.0.0```, resulting ```rmtree``` to fail.
> fix version parsing
